name: AnimeViewer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test Android
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    # Step 3: Cache Gradle dependencies
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

      # Step 4: Grant execution permissions to gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    # Step 5: Run tests
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest

  deploy:
    name: Deploy APK
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Debug APK
        path: app/build/outputs/apk/debug/*.apk
